version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run:
          command: sudo composer self-update
          working_directory: ./src
      # - run:
      #     command: composer install -n --prefer-dist
      #     working_directory: ./src
      - run:
          command: php artisan config:cache
          working_directory: ./src
      - run:
          command: php artisan config:clear
          working_directory: ./src
      # - run: npm ci
      # - run: npm run dev
      # - run:
      #     command: php artisan config:cache
      #     working_directory: ./src
      # - run:
      #     command: php artisan config:clear
      #     working_directory: ./src
      - run:
          name: php test
          working_directory: ./src
          command: vendor/bin/phpunit tests/Feature
          #command: vendor/bin/phpunit # tests/Feature
      # - checkout
      # - run:
      #     command: sudo composer self-update
      # - run:
      #     command: composer install -n --prefer-dist
      # - run:
      #     command: npm ci
      #     working_directory: ./src
      # - run:
      #     command: npm run dev
      #     working_directory: ./src
      # - run:
      #     command: php artisan config:cache
      # - run:
      #     command: php artisan config:clear
      # - run: touch database/development.sqlite3
      # - run: php artisan migrate --env=testing --database=sqlite_testing --force
      # - run:
      #     name: php test
      #     command: vendor/bin/phpunit tests/Feature
